# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Up-and-Out Put Option price with a barrier
#'
#' @param Expiry Time to Maturity
#' @param Strike Strike price
#' @param Spot Spot price
#' @param b Barrier value
#' @param Vol Volatility
#' @param r Risk-free rate
#' @param NumberOfPaths Number of Monte-Carlo paths
#' @param LengthOfPath Number of Monte-Carlo paths
#' @export
#' @examples
#' getPutPrice(0.75, 150, 140, 160, 0.24, 0.07)
getPutPrice <- function(Expiry = 0.75, Strike = 150, Spot = 140, b = 160, Vol = 0.24, r = 0.07, NumberOfPaths = 10000L, LengthOfPath = 10000L) {
    .Call(`_UpOutPut_getPutPrice`, Expiry, Strike, Spot, b, Vol, r, NumberOfPaths, LengthOfPath)
}

