// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getPutPrice
double getPutPrice(double Expiry, double Strike, double Spot, double b, double Vol, double r, unsigned long NumberOfPaths, unsigned long LengthOfPath);
RcppExport SEXP _UpOutPut_getPutPrice(SEXP ExpirySEXP, SEXP StrikeSEXP, SEXP SpotSEXP, SEXP bSEXP, SEXP VolSEXP, SEXP rSEXP, SEXP NumberOfPathsSEXP, SEXP LengthOfPathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type Expiry(ExpirySEXP);
    Rcpp::traits::input_parameter< double >::type Strike(StrikeSEXP);
    Rcpp::traits::input_parameter< double >::type Spot(SpotSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type Vol(VolSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type NumberOfPaths(NumberOfPathsSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type LengthOfPath(LengthOfPathSEXP);
    rcpp_result_gen = Rcpp::wrap(getPutPrice(Expiry, Strike, Spot, b, Vol, r, NumberOfPaths, LengthOfPath));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_UpOutPut_getPutPrice", (DL_FUNC) &_UpOutPut_getPutPrice, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_UpOutPut(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
